<?xml version="1.0"?>
<package format="3">
  <name>system_launcher</name>
  <version>0.0.1</version>
  <description>System launcher for XLeRobot</description>
  <maintainer email="jinyoungk0126@gmail.com">Jinyoung</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
</package>
