<?xml version="1.0"?>
<package format="3">
  <name>slam_module</name>
  <version>0.0.1</version>
  <description>SLAM module for XLeRobot</description>
  <maintainer email="jinyoungk0126@gmail.com">Jinyoung</maintainer>
  <license>Apache-2.0</license>

  <depend>rclcpp</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
</package>
